# Day 4 Exercises
## Object Oriented Programming

#### 1. Create a class called `Book` that has the attributes title, author, pages, price. It also has the method get_price() which returns price, and set_price() to ensure price is numeric.

Then create two instances of this class:

b1:
* title -> 'Practical Programming'
* author -> 'Gries, Campbell, Montojo'
* pages -> 383
* price -> 50

b2:
* title -> 'Building a Career in Data Science'
* author -> 'Robinson, Nolis'
* pages -> 322
* price -> 40

In [1]:
# Your code goes here
class Book:
  def __init__(self, title, author, pages, price):
    self.title = title
    self.author = author
    self.pages = pages
    self.price = price

  def get_price(self):
    return self.price

  def set_price(self, price):
    self.price = price(int)
    return self.price


In [2]:
B1 = Book('Practical Programming', 'Gries, Campbell, Montojo', 383, 50)
B2 = Book('Building a Career in Data Science', 'Robinson, Nolis', 322, 40)

In [7]:
get_price = B1.get_price()
print(get_price)

50


#### 2. Create a `Phone` class that has the attributes model, id, name, brand and price. Create the getters and setters for each attribute. As well as the following methods: calculate_total which takes the price and calculates it by the tax argument.

In [8]:
# Your code goes here
class Phone:
  def __init__(self, model, id, name, brand, price):
    self.model = model
    self.id = id
    self.name = name
    self.brand = brand
    self.price = price

  def get_total(self, tax):
    self.tax = tax
    return self.price * tax


## Numpy

In [9]:
import numpy as np

#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:

[[0 1 2]

[3 4 5]]

In [10]:
# Your code goes here
array = np.array([0,1,2,3,4,5])


In [11]:
reshaped_array = array.reshape(2,3)
print(reshaped_array)

[[0 1 2]
 [3 4 5]]


#### 2. Create a 3×3 NumPy array of all True

*Hint! Use np.ones() with dtype=bool.*

In [12]:
# Your code goes here
array = np.ones((3,3), dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#### 3. Create a 1D array filled with zeros and another filled with ones

In [13]:
# Your code goes here
import numpy as np
zeros_array = np.zeros(5)
print("Array of zeros:", zeros_array)
ones_array = np.ones(7)
print("Array of ones:", ones_array)

Array of zeros: [0. 0. 0. 0. 0.]
Array of ones: [1. 1. 1. 1. 1. 1. 1.]


#### 4. Reverse a 1D NumPy array
Ex. arr = np.arange(10)

Output is [9 8 7 6 5 4 3 2 1 0]

*Hint! Use slicing with step = -1.*

In [14]:
arr = np.arange(10)
print("Original array:", arr)
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [ ]:
# Your code goes here

#### 5. Stack these arrays horizontally


a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [15]:
# Your code goes here

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_array = np.hstack((a, b))
print(stacked_array)

[1 2 3 4 5 6]


#### 6. Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

*   Add two NumPy arrays element by element.
*   Multiply two NumPy arrays element by element.

In [16]:
# Your code goes here

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

sum_array = a + b
print("Element-by-element sum:", sum_array)

Element-by-element sum: [5 7 9]


In [17]:
product_array = a * b
print("Element-by-element:", product_array)

Element-by-element: [ 4 10 18]
